import { rgb } from 'pdf-lib'
import type { PDFPage, PDFFont } from 'pdf-lib'
import { pdfColor, pdfSize } from '@/tokens'

const BRAND_TEAL = rgb(...pdfColor.brandTeal)

/**
 * Draws the Life Relay logo mark (relay baton with arcs) at the given position.
 * The mark is drawn at a fixed aspect ratio within the given size.
 * pdf-lib can't draw curves, so we approximate the arcs with line segments
 * and draw the baton as a thick angled line with rounded caps.
 */
export function drawLifeRelayMark(page: PDFPage, x: number, y: number, size: number) {
  const s = size / 512
  const white = rgb(...pdfColor.white)

  // Background square
  page.drawRectangle({
    x,
    y: y - size,
    width: size,
    height: size,
    color: BRAND_TEAL,
  })

  // Left arc (giver) — approximated with line segments
  // Curve from (120,360) to (256,140) via bezier-like points
  const leftArcPoints = [
    { px: 120, py: 360 },
    { px: 120, py: 300 },
    { px: 130, py: 240 },
    { px: 155, py: 195 },
    { px: 190, py: 160 },
    { px: 225, py: 145 },
    { px: 256, py: 140 },
  ]
  for (let i = 0; i < leftArcPoints.length - 1; i++) {
    const a = leftArcPoints[i]
    const b = leftArcPoints[i + 1]
    page.drawLine({
      start: { x: x + a.px * s, y: y - size + (512 - a.py) * s },
      end:   { x: x + b.px * s, y: y - size + (512 - b.py) * s },
      thickness: 32 * s,
      color: white,
      opacity: 0.3,
    })
  }

  // Right arc (receiver) — approximated with line segments
  // Curve from (256,372) to (392,152)
  const rightArcPoints = [
    { px: 256, py: 372 },
    { px: 287, py: 372 },
    { px: 325, py: 357 },
    { px: 355, py: 320 },
    { px: 378, py: 265 },
    { px: 390, py: 205 },
    { px: 392, py: 152 },
  ]
  for (let i = 0; i < rightArcPoints.length - 1; i++) {
    const a = rightArcPoints[i]
    const b = rightArcPoints[i + 1]
    page.drawLine({
      start: { x: x + a.px * s, y: y - size + (512 - a.py) * s },
      end:   { x: x + b.px * s, y: y - size + (512 - b.py) * s },
      thickness: 32 * s,
      color: white,
      opacity: 0.3,
    })
  }

  // Baton — thick diagonal line (approximating rotated rounded rect)
  // From roughly (210,290) to (302,198) at -45 degrees
  page.drawLine({
    start: { x: x + 200 * s, y: y - size + (512 - 295) * s },
    end:   { x: x + 312 * s, y: y - size + (512 - 183) * s },
    thickness: 38 * s,
    color: white,
  })
}

/**
 * Draws the "Generated by Life Relay (liferelay.app)" branding line with date.
 */
export function drawGeneratedBy(
  page: PDFPage,
  font: PDFFont,
  pageWidth: number,
  y: number,
) {
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
  const dateLine = `Generated on ${dateStr}`
  const brandLine = 'Life Relay -- liferelay.app'
  const dateWidth = font.widthOfTextAtSize(dateLine, pdfSize.body)
  const brandWidth = font.widthOfTextAtSize(brandLine, pdfSize.bodyTiny)
  page.drawText(dateLine, {
    x: (pageWidth - dateWidth) / 2,
    y: y + 11,
    size: pdfSize.body,
    font,
    color: rgb(...pdfColor.textBrandDate),
  })
  page.drawText(brandLine, {
    x: (pageWidth - brandWidth) / 2,
    y,
    size: pdfSize.bodyTiny,
    font,
    color: rgb(...pdfColor.textGray),
  })
}
