import type { FormSectionSchema } from '@/models/FormSchema'

export const businessOwnershipSchema: FormSectionSchema = {
  sectionKey: 'businessOwnership',
  title: 'Business Ownership',
  description: 'Business interests, ownership, and the information needed to wind down or transfer the business',
  isArray: true,
  arrayItemLabel: (_, item) => item?.businessName || 'Business',
  pdfGroup: 'Property & Household',
  fields: [
    {
      name: 'businessName',
      label: 'Business Name',
      type: 'text',
      placeholder: 'Business Name',
      colSpan: 1,
    },
    {
      name: 'entityType',
      label: 'Entity Type',
      type: 'select',
      colSpan: 1,
      options: [
        { label: '', value: '' },
        { label: 'Sole Proprietorship', value: 'sole-prop' },
        { label: 'LLC (Single-Member)', value: 'llc-single' },
        { label: 'LLC (Multi-Member)', value: 'llc-multi' },
        { label: 'S-Corporation', value: 's-corp' },
        { label: 'C-Corporation', value: 'c-corp' },
        { label: 'Partnership', value: 'partnership' },
        { label: 'Nonprofit', value: 'nonprofit' },
        { label: 'Other', value: 'other' },
      ],
    },
    {
      name: 'ownershipPercentage',
      label: 'Ownership %',
      type: 'text',
      placeholder: '50, 100, etc.',
      colSpan: 1,
    },
    {
      name: 'ein',
      label: 'EIN / Tax ID',
      type: 'text',
      placeholder: 'XX-XXXXXXX',
      colSpan: 1,
    },
    {
      name: 'formationDate',
      label: 'Formation Date',
      type: 'text',
      placeholder: 'e.g. 2020 or 2020-03-15',
      colSpan: 1,
    },
    {
      name: 'stateOfFormation',
      label: 'State of Formation',
      type: 'text',
      placeholder: 'e.g. Delaware, Texas',
      colSpan: 1,
    },
    {
      name: 'registeredAgent',
      label: 'Registered Agent',
      type: 'text',
      placeholder: 'e.g. Self, LegalZoom, Northwest Registered Agent',
      colSpan: 2,
      fullWidth: true,
    },

    // ===== Documents & Filings =====
    {
      sectionDivider: {
        label: 'Documents & Filings',
        collapsible: true,
      },
    },
    {
      name: 'operatingAgreementLocation',
      label: 'Operating Agreement / Bylaws Location',
      type: 'text',
      placeholder: 'e.g. Home safe, with attorney, in business filing cabinet',
      colSpan: 2,
      fullWidth: true,
    },
    {
      name: 'formationDocsLocation',
      label: 'Formation / Articles Location',
      type: 'text',
      placeholder: 'e.g. State filing online, copy in home safe',
      colSpan: 2,
      fullWidth: true,
    },
    {
      name: 'businessAccountInfo',
      label: 'Business Bank Account',
      type: 'text',
      placeholder: 'e.g. See Financial Accounts → Business Checking at Example Bank',
      colSpan: 2,
      fullWidth: true,
      helpText: 'Reference the entry in Financial Accounts rather than duplicating info',
    },

    // ===== Partners & Key People =====
    {
      sectionDivider: {
        label: 'Partners & Key People',
        collapsible: true,
      },
    },
    {
      name: 'partners',
      label: 'Partners / Co-Owners',
      type: 'textarea',
      placeholder: 'Names, ownership %, contact info — or reference Important Contacts',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
    {
      name: 'keyEmployees',
      label: 'Key Employees / Contractors',
      type: 'textarea',
      placeholder: 'Anyone whose departure would significantly impact operations',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
    {
      name: 'professionalContacts',
      label: 'Accountant / Attorney / Bookkeeper',
      type: 'textarea',
      placeholder: 'Names and roles — full contact details in Important Contacts',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },

    // ===== Succession Plan =====
    {
      sectionDivider: {
        label: 'Succession Plan',
        collapsible: true,
      },
    },
    {
      name: 'successionPlan',
      label: 'On Death/Incapacity, the Business Should',
      type: 'select',
      colSpan: 2,
      fullWidth: true,
      options: [
        { label: '', value: '' },
        { label: 'Be wound down / dissolved', value: 'dissolve' },
        { label: 'Be sold to partner(s) per buy-sell agreement', value: 'sell-partner' },
        { label: 'Be sold to a third party', value: 'sell-external' },
        { label: 'Be transferred to a specific heir', value: 'transfer-heir' },
        { label: 'Continue under operating agreement succession terms', value: 'continue-per-agreement' },
        { label: 'No plan in place yet', value: 'none' },
      ],
    },
    {
      name: 'successionDetails',
      label: 'Succession Details / Instructions',
      type: 'textarea',
      placeholder: 'e.g. Buy-sell agreement funded by life insurance — see Life Insurance section. Partner Jane Smith has right of first refusal. Transfer client contracts to executor for orderly handoff.',
      colSpan: 2,
      fullWidth: true,
      rows: 3,
    },
    {
      name: 'urgentActions',
      label: 'Urgent Actions on My Death',
      type: 'textarea',
      placeholder: 'e.g. Notify clients within 30 days. Continue payroll for 60 days. File final tax return. Cancel software subscriptions.',
      colSpan: 2,
      fullWidth: true,
      rows: 3,
      helpText: 'Time-sensitive things that must happen quickly',
    },

    {
      name: 'notes',
      label: 'Notes',
      type: 'textarea',
      placeholder: 'Anything else useful',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
  ],
}
