/**
 * Updated Crypto Assets Form Schema
 */

import type { FormSectionSchema } from '@/models/FormSchema'

// ---------------------------------------------------------------------------
// Reusable Crypto Key Schema
// ---------------------------------------------------------------------------
const cryptoKeySchema: FormSectionSchema = {
  sectionKey: 'cryptoKey',
  title: 'Crypto Key',
  isArray: true,
  arrayItemLabel: (index, item) => item.walletLabel || `Key ${index + 1}`,
  initializeItem: () => ({
    id: `key-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    walletLabel: '',
    vendor: '',
    keyType: '',
    provider: '',
    providerUrl: '',
    providerContact: '',
    publicKey: '',
    hardwareModel: '',
    hardwareLocation: '',
    network: '',
    keyBackupType: '',
    keyBackupLocation: '',
    keyBackupPassword: '',
    keyBackupPasswordManualEntry: false,

    password: '',
    passwordManualEntry: false,
    pin: '',
    pinManualEntry: false,
    passphrase: '',
    passphraseManualEntry: false,
    seedPhrase: '',
    seedPhraseManualEntry: false,
    derivationPath: '',

    physicalKeyLocations: [],

    notes: '',
  }),
  fields: [
    {
      name: 'walletLabel',
      label: 'Key Nickname',
      type: 'text',
      placeholder: 'e.g., Ledger 1, Coldcard Backup',
      colSpan: 1,
    },
    {
      name: 'vendor',
      label: 'Vendor/Brand/Application',
      type: 'text',
      placeholder: 'Ledger, Trezor, Coldcard, Sparrow, etc.',
      colSpan: 1,
    },
    {
      name: 'hardwareModel',
      label: 'Device Model',
      type: 'text',
      placeholder: 'e.g., Ledger Nano X, Trezor Model T, Coldcard Mk4',
      colSpan: 1,
      visible: { field: 'keyType', operator: 'equals', value: 'Hardware' },
    },
    {
      name: 'hardwareLocation',
      label: 'Device Location',
      type: 'text',
      placeholder: 'Where is the physical device stored?',
      colSpan: 1,
      visible: { field: 'keyType', operator: 'equals', value: 'Hardware' },
    },
    {
      name: 'keyType',
      label: 'Key Type',
      type: 'select',
      colSpan: 1,
      options: [
        { label: 'Select type', value: '' },
        { label: 'Hardware Wallet', value: 'Hardware' },
        { label: 'Software Wallet', value: 'Software' },
        { label: 'Paper Wallet', value: 'Paper' },
        { label: 'Metal Backup', value: 'Metal' },
        { label: 'Provider (Casa, Unchained, etc.)', value: 'Provider' },
        { label: 'Other', value: 'Other' },
      ],
    },

    // Provider section
    {
      name: 'provider',
      label: 'Provider Name',
      type: 'text',
      placeholder: 'Casa, Unchained Capital, etc.',
      colSpan: 1,
      visible: { field: 'keyType', operator: 'equals', value: 'Provider' },
    },
    {
      name: 'providerUrl',
      label: 'Provider Website',
      type: 'text',
      placeholder: 'https://example.com',
      colSpan: 1,
      visible: { field: 'keyType', operator: 'equals', value: 'Provider' },
    },
    {
      name: 'providerContact',
      label: 'Provider Contact',
      type: 'text',
      placeholder: 'Email, phone, or support account',
      colSpan: 2,
      fullWidth: true,
      visible: { field: 'keyType', operator: 'equals', value: 'Provider' },
    },

    // Public key + network
    {
      name: 'publicKey',
      label: 'Public Key',
      type: 'text',
      placeholder: 'Public key or xpub',
      colSpan: 2,
      fullWidth: true,
    },

    // Backup expandable section
    {
      name: 'keyBackupType',
      label: 'Backup Type',
      type: 'text',
      placeholder: 'Coldcard 7z, BitBox Backup, etc.',
      colSpan: 1,
      expandableSectionId: 'keyBackup',
      expandableSectionLabel: 'Key Backup File',
      expandableSectionDefaultExpanded: false,
    },
    {
      name: 'keyBackupLocation',
      label: 'Backup Location',
      type: 'text',
      placeholder: 'Where the backup is stored',
      colSpan: 2,
      fullWidth: true,
      expandableSectionId: 'keyBackup',
    },
    {
      name: 'keyBackupPassword',
      label: 'Backup Password',
      type: 'password',
      placeholder: 'Password for encrypted backup file',
      colSpan: 2,
      fullWidth: true,
      manualEntry: true,
      expandableSectionId: 'keyBackup',
    },

    // Security info divider
    {
      name: '_keySecurityDivider',
      type: 'text',
      label: '',
      sectionDivider: { label: 'Key Security Information' },
    },

    {
      name: 'password',
      label: 'Password',
      type: 'password',
      placeholder: 'Wallet password (if applicable)',
      colSpan: 1,
      manualEntry: true,
    },
    {
      name: 'pin',
      label: 'PIN',
      type: 'password',
      placeholder: 'PIN code',
      colSpan: 1,
      manualEntry: true,
    },
    {
      name: 'seedPhrase',
      label: 'Seed Phrase (12 or 24 words)',
      type: 'textarea',
      placeholder: 'Enter 12 or 24 word seed phrase (optional - consider storing separately)',
      rows: 2,
      colSpan: 2,
      fullWidth: true,
      manualEntry: true,
    },
    {
      name: 'passphrase',
      label: 'BIP39 Passphrase',
      type: 'password',
      placeholder: 'BIP39 passphrase (25th word)',
      colSpan: 1,
      manualEntry: true,
    },
    {
      name: 'derivationPath',
      label: 'Derivation Path',
      type: 'text',
      placeholder: "m/84'/0'/0'",
      colSpan: 1,
    },

    // Physical key storage
    {
      name: 'physicalKeyLocations',
      label: 'Physical Key Locations',
      type: 'array',
      arraySchema: {
        sectionKey: 'physicalKeyLocation',
        title: 'Physical Key Location',
        isArray: true,
        arrayItemLabel: (index, item) => item.location || `Location ${index + 1}`,
        initializeItem: () => ({
          location: '',
          description: '',
        }),
        fields: [
          {
            name: 'location',
            label: 'Location',
            type: 'text',
            placeholder: 'e.g., Bank safe deposit box',
            colSpan: 2,
          },
          {
            name: 'description',
            label: 'Description',
            type: 'text',
            placeholder: 'e.g., Hardware wallet, metal backup, paper wallet, etc.',
            colSpan: 2,
          },
          {
            name: 'accessInstructions',
            label: 'Access Instructions',
            type: 'textarea',
            placeholder: 'Access instructions',
            colSpan: 2,
            fullWidth: true,
          },
        ],
      },
      colSpan: 2,
      fullWidth: true,
    },
    {
      name: 'notes',
      label: 'Key Notes',
      type: 'textarea',
      placeholder: 'Additional notes about this key',
      rows: 2,
      colSpan: 2,
      fullWidth: true,
    },
  ],
}

// ---------------------------------------------------------------------------
// Crypto Asset Schema
// ---------------------------------------------------------------------------
export const cryptoAssetsSchema: FormSectionSchema = {
  sectionKey: 'cryptoAssets',
  title: 'Cryptocurrency Assets',
  description: 'Bitcoin, Ethereum, wallets, seed phrases, and recovery information.',
  pdfGroup: 'Digital & Crypto Assets',
  isArray: true,
  arrayItemLabel: (index, item) => item.type || `Asset ${index + 1}`,
  initializeItem: () => ({
    nickname: '',
    type: '',
    blockchain: '',
    blockchainOther: '',
    walletApp: '',
    walletAppOther: '',
    approximateHoldings: '',
    network: '',
    storageType: 'single-sig',
    isCustodial: false,

    walletAddress: '',
    exchange: '',
    exchangeAccountId: '',
    exchangeEmail: '',
    exchange2faMethod: '',
    exchange2faRecovery: '',
    exchangeBeneficiary: '',
    exchangeDeathClaimProcess: '',

    walletBackupFileName: '',
    walletBackupFileType: '',
    walletBackupFileLocation: '',
    walletBackupFilePassword: '',
    walletBackupFilePasswordManualEntry: false,

    singleKey: [cryptoKeySchema.initializeItem!()],

    multiSigConfig: {
      requiredSignatures: 0,
      totalKeys: 0,
      keys: [],
    },

    recoveryInstructions: '',
    heirInstructions: '',
    heirInstructionsManualEntry: false,
    notes: '',
  }),
  fields: [
    {
      name: 'nickname',
      label: 'Asset Nickname',
      type: 'text',
      colSpan: 1,
      placeholder: 'My BTC Savings, ETH Cold Wallet, etc.',
    },
    {
      name: 'type',
      label: 'Cryptocurrency',
      type: 'text',
      placeholder: 'Bitcoin, Ethereum, etc.',
      colSpan: 1,
    },
    {
      name: 'blockchain',
      label: 'Blockchain Network',
      type: 'select',
      colSpan: 1,
      options: [
        { label: 'Select network', value: '' },
        { label: 'Bitcoin', value: 'Bitcoin' },
        { label: 'Ethereum', value: 'Ethereum' },
        { label: 'Solana', value: 'Solana' },
        { label: 'Cardano', value: 'Cardano' },
        { label: 'Polygon', value: 'Polygon' },
        { label: 'Avalanche', value: 'Avalanche' },
        { label: 'Arbitrum', value: 'Arbitrum' },
        { label: 'Base', value: 'Base' },
        { label: 'Optimism', value: 'Optimism' },
        { label: 'BNB Chain', value: 'BNB Chain' },
        { label: 'Multiple Chains', value: 'Multiple' },
        { label: 'Other', value: 'Other' },
      ],
    },
    {
      name: 'blockchainOther',
      label: 'Other Network',
      type: 'text',
      placeholder: 'Specify blockchain network',
      colSpan: 1,
      visible: { field: 'blockchain', operator: 'equals', value: 'Other' },
    },
    {
      name: 'approximateHoldings',
      label: 'Approximate Holdings',
      type: 'text',
      placeholder: 'e.g., 2.5 BTC, ~$50,000 worth of ETH',
      colSpan: 1,
      helpText: 'Approximate only — helps your executor understand scale and priority.',
    },
    {
      name: 'storageType',
      label: 'Storage Type',
      type: 'select',
      colSpan: 1,
      options: [
        { label: 'Single Signature Wallet', value: 'single-sig' },
        { label: 'Multi-Signature Wallet', value: 'multi-sig' },
        { label: 'Exchange', value: 'exchange' },
      ],
    },
    {
      name: 'isCustodial',
      label: 'Is Custodial?',
      type: 'checkbox',
      colSpan: 1,
      visible: { field: 'storageType', operator: 'equals', value: 'exchange' },
    },

    // Wallet app (non-exchange)
    {
      name: 'walletApp',
      label: 'Wallet Application',
      type: 'select',
      colSpan: 1,
      visible: { field: 'storageType', operator: 'notEquals', value: 'exchange' },
      options: [
        { label: 'Select wallet', value: '' },
        { label: 'Ledger Live', value: 'Ledger Live' },
        { label: 'Trezor Suite', value: 'Trezor Suite' },
        { label: 'Sparrow', value: 'Sparrow' },
        { label: 'Electrum', value: 'Electrum' },
        { label: 'MetaMask', value: 'MetaMask' },
        { label: 'Phantom', value: 'Phantom' },
        { label: 'BlueWallet', value: 'BlueWallet' },
        { label: 'Exodus', value: 'Exodus' },
        { label: 'Trust Wallet', value: 'Trust Wallet' },
        { label: 'Rabby', value: 'Rabby' },
        { label: 'Other', value: 'Other' },
      ],
    },
    {
      name: 'walletAppOther',
      label: 'Other Wallet',
      type: 'text',
      placeholder: 'Specify wallet application',
      colSpan: 1,
      visible: {
        field: 'walletApp', operator: 'equals', value: 'Other',
        and: [{ field: 'storageType', operator: 'notEquals', value: 'exchange' }],
      },
    },

    // Exchange fields
    {
      name: 'exchange',
      label: 'Exchange Name',
      type: 'text',
      placeholder: 'Coinbase, Kraken, etc.',
      colSpan: 1,
      visible: { field: 'storageType', operator: 'equals', value: 'exchange' },
    },
    {
      name: 'exchangeAccountId',
      label: 'Account ID / Username',
      type: 'text',
      colSpan: 1,
      placeholder: 'User ID or login identifier',
      visible: { field: 'storageType', operator: 'equals', value: 'exchange' },
    },
    {
      name: 'exchangeEmail',
      label: 'Account Email',
      type: 'email',
      placeholder: 'Email used for exchange account',
      colSpan: 1,
      visible: { field: 'storageType', operator: 'equals', value: 'exchange' },
    },
    {
      name: 'exchange2faMethod',
      label: '2FA Method',
      type: 'select',
      colSpan: 1,
      visible: { field: 'storageType', operator: 'equals', value: 'exchange' },
      options: [
        { label: 'Select method', value: '' },
        { label: 'Authenticator App', value: 'authenticator' },
        { label: 'SMS', value: 'sms' },
        { label: 'Hardware Security Key', value: 'hardware-key' },
        { label: 'Email', value: 'email' },
        { label: 'None', value: 'none' },
      ],
    },
    {
      name: 'exchange2faRecovery',
      label: '2FA Recovery Notes',
      type: 'textarea',
      placeholder: 'Where are backup codes stored? Which authenticator app?',
      rows: 2,
      colSpan: 2,
      fullWidth: true,
      visible: { field: 'storageType', operator: 'equals', value: 'exchange' },
    },
    {
      name: 'exchangeBeneficiary',
      label: 'Beneficiary Designated on Exchange?',
      type: 'select',
      colSpan: 1,
      visible: { field: 'storageType', operator: 'equals', value: 'exchange' },
      options: [
        { label: 'Unknown', value: '' },
        { label: 'Yes', value: 'yes' },
        { label: 'No', value: 'no' },
        { label: 'Not Available', value: 'na' },
      ],
    },
    {
      name: 'exchangeDeathClaimProcess',
      label: 'Death Claim / Inheritance Process',
      type: 'textarea',
      placeholder: 'Notes on how heirs should contact the exchange to claim assets',
      rows: 2,
      colSpan: 2,
      fullWidth: true,
      visible: { field: 'storageType', operator: 'equals', value: 'exchange' },
    },

    // Wallet address (non-exchange only)
    {
      name: 'walletAddress',
      label: 'Wallet Address',
      type: 'text',
      colSpan: 2,
      fullWidth: true,
      placeholder: 'Wallet address or public key',
      visible: { field: 'storageType', operator: 'notEquals', value: 'exchange' },
    },

    // Backup section (non-exchange)
    {
      name: 'walletBackupFileName',
      label: 'Backup File Name',
      type: 'text',
      placeholder: 'e.g., sparrow-backup.json',
      colSpan: 1,
      expandableSectionId: 'walletBackup',
      expandableSectionLabel: 'Wallet Backup File',
      expandableSectionDefaultExpanded: false,
      visible: { field: 'storageType', operator: 'notEquals', value: 'exchange' },
    },
    {
      name: 'walletBackupFileType',
      label: 'Backup File Type',
      type: 'text',
      placeholder: 'Sparrow, Electrum, etc.',
      colSpan: 1,
      visible: { field: 'storageType', operator: 'notEquals', value: 'exchange' },
      expandableSectionId: 'walletBackup',
    },
    {
      name: 'walletBackupFileLocation',
      label: 'Backup File Location',
      type: 'text',
      placeholder: 'Where the backup file is stored',
      colSpan: 2,
      fullWidth: true,
      visible: { field: 'storageType', operator: 'notEquals', value: 'exchange' },
      expandableSectionId: 'walletBackup',
    },
    {
      name: 'walletBackupFilePassword',
      label: 'Backup File Password',
      type: 'password',
      placeholder: 'Password for encrypted backup file',
      colSpan: 2,
      fullWidth: true,
      manualEntry: true,
      visible: { field: 'storageType', operator: 'notEquals', value: 'exchange' },
      expandableSectionId: 'walletBackup',
    },

    // Multi-sig config
    {
      name: 'multiSigConfig.requiredSignatures',
      label: 'Required Signatures (M)',
      type: 'number',
      placeholder: 'e.g., 2',
      colSpan: 1,
      visible: { field: 'storageType', operator: 'equals', value: 'multi-sig' },
    },
    {
      name: 'multiSigConfig.totalKeys',
      label: 'Total Keys (N)',
      type: 'number',
      placeholder: 'e.g., 3',
      colSpan: 1,
      visible: { field: 'storageType', operator: 'equals', value: 'multi-sig' },
    },
    {
      name: 'multiSigConfig.keys',
      label: 'Multi-Signature Keys',
      type: 'array',
      arraySchema: cryptoKeySchema,
      colSpan: 2,
      fullWidth: true,
      visible: { field: 'storageType', operator: 'equals', value: 'multi-sig' },
    },

    // Single-sig (exactly 1 key)
    {
      name: 'singleKey',
      label: 'Wallet Key',
      type: 'array',
      arraySchema: cryptoKeySchema,
      arrayAllowAdd: false,
      arrayAllowRemove: false,
      colSpan: 2,
      fullWidth: true,
      visible: { field: 'storageType', operator: 'equals', value: 'single-sig' },
    },

    // Recovery Instructions
    {
      name: '_recoveryInstructionsButton',
      type: 'custom',
      label: '',
      component: 'RecoveryInstructionsButton',
      componentProps: {
        label: 'Generate Recommended Recovery Instructions',
        helpText: 'Pre-populate recommended instructions.',
      },
      colSpan: 2,
      fullWidth: true,
      visible: { field: 'storageType', operator: 'notEquals', value: 'exchange' },
    },
    {
      name: 'recoveryInstructions',
      label: 'Recovery Instructions',
      type: 'textarea',
      placeholder: 'Step-by-step recovery instructions for family members. Click the button above to generate recommended instructions based on wallet type.',
      rows: 6,
      colSpan: 2,
      fullWidth: true,
      visible: { field: 'storageType', operator: 'notEquals', value: 'exchange' },
    },

    // Heir instructions
    {
      name: '_heirInstructionsDivider',
      type: 'text',
      label: '',
      sectionDivider: { label: 'Instructions for Your Heir' },
    },
    {
      name: 'heirInstructions',
      label: 'Step-by-Step Instructions for Heir',
      type: 'textarea',
      placeholder: 'Write clear instructions a non-technical person can follow.\n\nExample:\n1. Find the Ledger device in the office safe (combination: ___)\n2. Connect to computer via USB cable\n3. Open Ledger Live application (installed on desktop)\n4. Enter PIN: ___ (written on card in safe)\n5. Navigate to Bitcoin account\n6. Send to [attorney/beneficiary wallet address]',
      rows: 8,
      colSpan: 2,
      fullWidth: true,
      manualEntry: true,
    },

    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Additional notes about this crypto asset',
      rows: 2,
      colSpan: 2,
      fullWidth: true,
    },
  ],
}
