import type { FormSectionSchema } from '@/models/FormSchema'

export const finalWishesAndServicesSchema: FormSectionSchema = {
  sectionKey: 'finalWishesAndServices',
  title: 'Final Wishes & Services',
  description: 'Funeral, burial, memorial service preferences, obituary, and other final instructions for each person',
  isArray: true,
  arrayItemLabel: (index) => `Final Wishes ${index + 1}`,
  pdfGroup: 'Final Wishes',
  fields: [
    {
      name: 'personId',
      label: 'Person',
      type: 'custom',
      component: 'PersonSelector',
      colSpan: 2,
      fullWidth: true,
    },
    {
      sectionDivider: {
        label: 'Burial & Cremation Preferences',
      },
    },
    {
      name: 'burialOrCremation',
      label: 'Preference',
      type: 'select',
      colSpan: 1,
      options: [
        { label: 'Select preference', value: '' },
        { label: 'Burial', value: 'Burial' },
        { label: 'Cremation', value: 'Cremation' },
        { label: 'Green Burial', value: 'Green Burial' },
        { label: 'Donation to Science', value: 'Donation to Science' },
        { label: 'Other', value: 'Other' },
      ],
    },
    {
      name: 'cemetery',
      label: 'Cemetery / Location',
      type: 'text',
      placeholder: 'Cemetery name and location',
      colSpan: 1,
    },
    {
      name: 'plotLocation',
      label: 'Plot / Niche Details',
      type: 'text',
      placeholder: 'Plot number, section, etc.',
      colSpan: 1,
    },
    {
      sectionDivider: {
        label: 'Service & Memorial',
      },
    },
    {
      name: 'funeralArrangements',
      label: 'Funeral Arrangements',
      type: 'textarea',
      placeholder: 'Funeral arrangement preferences (funeral home, type of service, etc.)',
      colSpan: 2,
      fullWidth: true,
      rows: 3,
    },
    {
      name: 'servicePreferences',
      label: 'Service Preferences',
      type: 'textarea',
      placeholder: 'Service type, location, and preferences',
      colSpan: 2,
      fullWidth: true,
      rows: 3,
    },
    {
      name: 'music',
      label: 'Music Preferences',
      type: 'textarea',
      placeholder: 'Preferred music or songs',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
    {
      name: 'readings',
      label: 'Readings or Verses',
      type: 'textarea',
      placeholder: 'Preferred readings, verses, or quotes',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
    {
      sectionDivider: {
        label: 'Obituary & Online Presence',
      },
    },
    {
      name: 'obituary',
      label: 'Obituary',
      type: 'textarea',
      placeholder: 'Obituary information or preferences',
      colSpan: 2,
      fullWidth: true,
      rows: 3,
    },
    {
      name: 'socialMedia',
      label: 'Social Media Instructions',
      type: 'textarea',
      placeholder: 'How to handle social media accounts (memorialize, delete, etc.)',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
    {
      name: 'otherInstructions',
      label: 'Other Instructions',
      type: 'textarea',
      placeholder: 'Any other final instructions or preferences',
      colSpan: 2,
      fullWidth: true,
      rows: 3,
    },
    {
      name: 'notes',
      label: 'Notes',
      type: 'textarea',
      placeholder: 'Additional notes',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
  ],
}
