import type { FormSectionSchema } from '@/models/FormSchema'

export const healthInsuranceSchema: FormSectionSchema = {
  sectionKey: 'healthInsurance',
  title: 'Health Insurance',
  description: 'Health insurance policies and covered members',
  isArray: true,
  arrayItemLabel: (index, item) => item?.provider || `Policy ${index + 1}`,
  pdfGroup: 'Insurance, Medical & Benefits',
  fields: [
    {
      name: 'provider',
      label: 'Provider',
      type: 'text',
      placeholder: 'Insurance Provider',
      colSpan: 1,
    },
    {
      name: 'planType',
      label: 'Plan Type',
      type: 'select',
      colSpan: 1,
      options: [
        { label: '', value: '' },
        { label: 'PPO', value: 'PPO' },
        { label: 'HMO', value: 'HMO' },
        { label: 'EPO', value: 'EPO' },
        { label: 'POS', value: 'POS' },
        { label: 'HDHP', value: 'HDHP' },
        { label: 'Medicare', value: 'Medicare' },
        { label: 'Medicaid', value: 'Medicaid' },
        { label: 'Dental', value: 'Dental' },
        { label: 'Vision', value: 'Vision' },
        { label: 'Other', value: 'Other' },
      ],
    },
    {
      name: 'policyNumber',
      label: 'Policy Number',
      type: 'text',
      placeholder: 'Policy #',
      colSpan: 1,
    },
    {
      name: 'groupNumber',
      label: 'Group Number',
      type: 'text',
      placeholder: 'Group #',
      colSpan: 1,
    },
    {
      name: 'contactPhone',
      label: 'Contact Phone',
      type: 'tel',
      placeholder: '(555) 123-4567',
      colSpan: 1,
    },
    {
      name: 'coveredMembers',
      label: 'Covered Members',
      type: 'text',
      placeholder: 'e.g. John, Jane, Alex, Sam',
      colSpan: 1,
      helpText: 'Names of people covered under this policy',
    },
    {
      name: 'notes',
      label: 'Notes',
      type: 'textarea',
      placeholder: 'Additional notes (deductible, copay, etc.)',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
  ],
}
