import type { FormSectionSchema } from '@/models/FormSchema'

export const peopleSchema: FormSectionSchema = {
  sectionKey: 'people',
  title: 'People & Personal Information',
  description: 'Manage people in your legacy plan with their personal information (self, spouse, etc.)',
  isArray: true,
  arrayItemLabel: (index, item) => item.name || `Person ${index + 1}`,
  initializeItem: () => ({
    id: `person-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    name: '',
    dateOfBirth: '',
    socialSecurityNumber: '',
    address: '',
    phone: '',
    email: '',
    notes: '',
  }),
  pdfGroup: 'People & Contacts',
  fields: [
    {
      name: 'name',
      label: 'Full Name',
      type: 'text',
      placeholder: 'Full name',
      colSpan: 1,
    },
    {
      name: 'dateOfBirth',
      label: 'Date of Birth',
      type: 'date',
      colSpan: 1,
    },
    {
      name: 'socialSecurityNumber',
      label: 'Social Security Number',
      type: 'password',
      placeholder: 'XXX-XX-XXXX',
      colSpan: 1,
      manualEntry: true,
    },
    {
      name: 'address',
      label: 'Address',
      type: 'textarea',
      placeholder: 'Street address, City, State, ZIP',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
    {
      name: 'phone',
      label: 'Phone Number',
      type: 'tel',
      placeholder: '(555) 123-4567',
      colSpan: 1,
    },
    {
      name: 'email',
      label: 'Email',
      type: 'email',
      placeholder: 'email@example.com',
      colSpan: 1,
    },
    {
      name: 'notes',
      label: 'Notes',
      type: 'textarea',
      placeholder: 'Additional notes',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
  ],
}

