/**
 * Phones Form Schema
 */

import type { FormSectionSchema } from '@/models/FormSchema'

export const phonesSchema: FormSectionSchema = {
  sectionKey: 'phones',
  title: 'Phones',
  description: 'Phone access information including PINs, passcodes, cloud accounts, and recovery information',
  isArray: true,
  arrayItemLabel: (index, item) => item.phoneName || `Phone ${index + 1}`,
  pdfGroup: 'Security & Access',
  fields: [
    {
      name: 'phoneName',
      label: 'Phone Name/Model',
      type: 'text',
      placeholder: 'e.g., iPhone 14 Pro, Samsung Galaxy S23',
      colSpan: 1,
    },
    {
      name: 'phoneNumber',
      label: 'Phone Number',
      type: 'tel',
      placeholder: '(555) 123-4567',
      colSpan: 1,
    },
    {
      name: 'carrier',
      label: 'Carrier',
      type: 'text',
      placeholder: 'e.g., Verizon, AT&T, T-Mobile',
      colSpan: 1,
    },
    {
      name: 'imei',
      label: 'IMEI',
      type: 'text',
      placeholder: 'IMEI number',
      colSpan: 1,
    },
    // Unlock Information Section
    {
      name: '_unlockSection',
      label: '',
      type: 'text',
      sectionDivider: {
        label: 'Unlock Information',
        showBorder: true,
      },
      colSpan: 2,
      fullWidth: true,
      pdfSkipIfEmpty: true,
    },
    {
      name: 'pin',
      label: 'PIN',
      type: 'password',
      placeholder: 'Phone PIN',
      colSpan: 2,
      fullWidth: true,
      manualEntry: true,
    },
    {
      name: 'passcode',
      label: 'Passcode',
      type: 'password',
      placeholder: 'Phone passcode',
      colSpan: 2,
      fullWidth: true,
      manualEntry: true,
    },
    {
      name: 'biometricUnlock',
      label: 'Biometric Unlock',
      type: 'text',
      placeholder: 'Fingerprint, Face ID, etc.',
      colSpan: 2,
      fullWidth: true,
    },
    {
      name: 'simPin',
      label: 'SIM PIN',
      type: 'password',
      placeholder: 'SIM card PIN',
      colSpan: 2,
      fullWidth: true,
      manualEntry: true,
    },
    // Cloud Account Section
    {
      name: '_cloudSection',
      label: '',
      type: 'text',
      sectionDivider: {
        label: 'Cloud Account',
        showBorder: true,
      },
      colSpan: 2,
      fullWidth: true,
      pdfSkipIfEmpty: true,
    },
    {
      name: 'cloudAccount',
      label: 'Cloud Service',
      type: 'text',
      placeholder: 'iCloud, Google Account, etc.',
      colSpan: 1,
    },
    {
      name: 'cloudAccountEmail',
      label: 'Cloud Account Email',
      type: 'email',
      placeholder: 'email@example.com',
      colSpan: 1,
    },
    {
      name: 'cloudAccountPassword',
      label: 'Cloud Account Password',
      type: 'password',
      placeholder: 'Cloud account password',
      colSpan: 2,
      fullWidth: true,
      manualEntry: true,
      visible: {
        field: 'cloudAccount',
        operator: 'isNotEmpty',
      },
    },
    {
      name: 'encryptionPassword',
      label: 'Encryption Password',
      type: 'password',
      placeholder: 'Device encryption password',
      colSpan: 2,
      fullWidth: true,
      manualEntry: true,
    },
    {
      name: 'recoveryEmail',
      label: 'Recovery Email',
      type: 'email',
      placeholder: 'Recovery email address',
      colSpan: 1,
    },
    {
      name: 'recoveryPhone',
      label: 'Recovery Phone',
      type: 'tel',
      placeholder: 'Recovery phone number',
      colSpan: 1,
    },
    {
      name: 'twoFactorAuth',
      label: 'Two-Factor Authentication',
      type: 'text',
      placeholder: '2FA method or recovery codes location',
      colSpan: 2,
      fullWidth: true,
    },
    {
      name: 'backupLocation',
      label: 'Backup Location',
      type: 'text',
      placeholder: 'Where backups are stored',
      colSpan: 2,
      fullWidth: true,
    },
    {
      name: 'notes',
      label: 'Notes',
      type: 'textarea',
      placeholder: 'Additional notes',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
  ],
}

