import type { FormSectionSchema } from '@/models/FormSchema'

export const photosAndMediaSchema: FormSectionSchema = {
  sectionKey: 'photosAndMedia',
  title: 'Photos & Media',
  description: 'Location of photos, videos, and other media',
  isArray: false,
  pdfGroup: 'Final Wishes',
  fields: [
    {
      name: 'photoLocations',
      label: 'Photo Locations',
      type: 'textarea',
      placeholder: 'Physical locations of photos',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
    {
      name: 'digitalPhotoStorage',
      label: 'Digital Photo Storage',
      type: 'textarea',
      placeholder: 'Digital photo storage locations (cloud, hard drives, etc.)',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
    {
      name: 'photoAlbums',
      label: 'Photo Albums',
      type: 'textarea',
      placeholder: 'Photo album locations',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
    {
      name: 'videoLocations',
      label: 'Video Locations',
      type: 'textarea',
      placeholder: 'Video storage locations',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
    {
      name: 'importantMedia',
      label: 'Important Media',
      type: 'textarea',
      placeholder: 'Important media items and their locations',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
    {
      name: 'accessInstructions',
      label: 'Access Instructions',
      type: 'textarea',
      placeholder: 'Instructions for accessing media',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
    {
      name: 'notes',
      label: 'Notes',
      type: 'textarea',
      placeholder: 'Additional notes',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
  ],
}

