import type { FormSectionSchema } from '@/models/FormSchema'

export const physicalStorageLocationsSchema: FormSectionSchema = {
  sectionKey: 'physicalStorageLocations',
  title: 'Physical Storage Locations',
  description: 'Safes, safety deposit boxes, filing cabinets, and other physical locations where important items are stored',
  isArray: true,
  arrayItemLabel: (index, item) => item.name || `Location ${index + 1}`,
  initializeItem: () => ({
    id: `storage-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    name: '',
    locationType: '',
    location: '',
    combination: '',
    keyLocation: '',
    accessInstructions: '',
    notes: '',
  }),
  pdfGroup: 'Documents & Storage',
  fields: [
    {
      name: 'name',
      label: 'Location Name',
      type: 'text',
      placeholder: 'e.g., Home Safe, Bank Deposit Box, Filing Cabinet',
      colSpan: 1,
    },
    {
      name: 'locationType',
      label: 'Type',
      type: 'select',
      colSpan: 1,
      options: [
        { label: 'Select type', value: '' },
        { label: 'Safe', value: 'Safe' },
        { label: 'Safety Deposit Box', value: 'Safety Deposit Box' },
        { label: 'Filing Cabinet', value: 'Filing Cabinet' },
        { label: 'Fireproof Box', value: 'Fireproof Box' },
        { label: 'Attorney Office', value: 'Attorney Office' },
        { label: 'Storage Unit', value: 'Storage Unit' },
        { label: 'Other', value: 'Other' },
      ],
    },
    {
      name: 'location',
      label: 'Location / Address',
      type: 'textarea',
      placeholder: 'Where this storage is located (address, room, etc.)',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
    {
      name: 'combination',
      label: 'Combination / Code',
      type: 'password',
      placeholder: 'Safe combination or access code',
      manualEntry: true,
      colSpan: 1,
    },
    {
      name: 'keyLocation',
      label: 'Key Location',
      type: 'text',
      placeholder: 'Where the key is stored',
      colSpan: 1,
    },
    {
      name: 'accessInstructions',
      label: 'Access Instructions',
      type: 'textarea',
      placeholder: 'How to access this storage (hours, ID required, etc.)',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
    {
      name: 'notes',
      label: 'Notes',
      type: 'textarea',
      placeholder: 'Additional notes',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
  ],
}
