import type { FormSectionSchema } from '@/models/FormSchema'

export const trustsSchema: FormSectionSchema = {
  sectionKey: 'trusts',
  title: 'Trusts',
  description: 'Trust information including beneficiaries, trustees, and trust details. Add your trust attorney under Important Contacts.',
  isArray: true,
  arrayItemLabel: (index, item) => item.trustName || `Trust ${index + 1}`,
  initializeItem: () => ({
    id: `trust-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    trustName: '',
    trustType: '',
    dateCreated: '',
    trustNumber: '',
    grantor: '',
    trustee: '',
    successorTrustee: '',
    trustLocation: '',
    beneficiaries: [],
    purpose: '',
    distributionInstructions: '',
    notes: '',
  }),
  pdfGroup: 'Documents & Storage',
  fields: [
    {
      name: 'trustName',
      label: 'Trust Name',
      type: 'text',
      placeholder: 'e.g., Family Trust, Living Trust',
      colSpan: 1,
    },
    {
      name: 'trustType',
      label: 'Trust Type',
      type: 'select',
      colSpan: 1,
      options: [
        { label: 'Select type', value: '' },
        { label: 'Revocable Living Trust', value: 'Revocable Living Trust' },
        { label: 'Irrevocable Trust', value: 'Irrevocable Trust' },
        { label: 'Testamentary Trust', value: 'Testamentary Trust' },
        { label: 'Charitable Trust', value: 'Charitable Trust' },
        { label: 'Special Needs Trust', value: 'Special Needs Trust' },
        { label: 'Other', value: 'Other' },
      ],
    },
    {
      name: 'dateCreated',
      label: 'Date Created',
      type: 'date',
      colSpan: 1,
    },
    {
      name: 'trustNumber',
      label: 'Trust Number',
      type: 'text',
      placeholder: 'Trust account or document number',
      colSpan: 1,
    },
    {
      name: 'grantor',
      label: 'Grantor',
      type: 'text',
      placeholder: 'Person who created the trust',
      colSpan: 1,
    },
    {
      name: 'trustee',
      label: 'Trustee',
      type: 'text',
      placeholder: 'Person managing the trust',
      colSpan: 1,
    },
    {
      name: 'successorTrustee',
      label: 'Successor Trustee',
      type: 'text',
      placeholder: 'Backup trustee',
      colSpan: 1,
    },
    {
      name: 'trustLocation',
      label: 'Trust Document Location',
      type: 'text',
      placeholder: 'Where trust documents are stored',
      colSpan: 1,
    },
    {
      name: 'beneficiaries',
      label: 'Beneficiaries',
      type: 'custom',
      component: 'BeneficiarySelector',
      componentProps: {
        allowMultiple: true,
      },
      colSpan: 2,
      fullWidth: true,
    },
    {
      name: 'purpose',
      label: 'Purpose',
      type: 'textarea',
      placeholder: 'Purpose of the trust',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
    {
      name: 'distributionInstructions',
      label: 'Distribution Instructions',
      type: 'textarea',
      placeholder: 'How assets should be distributed',
      colSpan: 2,
      fullWidth: true,
      rows: 3,
    },
    {
      name: 'notes',
      label: 'Notes',
      type: 'textarea',
      placeholder: 'Additional notes',
      colSpan: 2,
      fullWidth: true,
      rows: 2,
    },
  ],
}
