// Icon mapping for sections and navigation
export const SECTION_ICONS: Record<string, string> = {
  'Dashboard': '📊',
  'People & Personal Info': '👤',
  'People & Personal Information': '👤',
  'Beneficiaries': '👥',
  'Trusts': '📜',
  'Pet Care': '🐾',
  'Photos & Media': '📷',
  'Password Vaults': '🔐',
  'Computer/Server': '💻',
  'Computers/Servers': '💻',
  'Phones': '📱',
  'Authenticator Apps': '🔑',
  'Safe Locations & Keys': '🗝️',
  'Life Insurance': '🛡️',
  'Health Insurance': '🏥',
  'Medical Info': '⚕️',
  'Medical Information': '⚕️',
  'Financial Accounts': '💰',
  'Credit Cards': '💳',
  'Debts & Loans': '📋',
  'Income Sources': '💵',
  'Utilities': '⚡',
  'Investment/Retirement Accounts': '📈',
  'Digital Assets': '🌐',
  'Cryptocurrency Assets': '₿',
  'Crypto Assets': '₿',
  'Employment Benefits': '💼',
  'Property & Real Estate': '🏠',
  'Vehicles': '🚗',
  'Asset Documents': '📄',
  'Business Ownership': '🏢',
  'Important Contacts': '📞',
  'Legal Documents': '⚖️',
  'Document Locations': '📁',
  'Documents Location': '📁',
  'Letter of Instruction': '✉️',
  'Final Instructions': '📝',
  'Burial Preferences': '🕊️',
  'Physical Storage': '🗄️',
  'Final Wishes & Services': '🕊️',
  'Retirement & Investment': '📈',
  'Utilities & Subscriptions': '⚡',
  'Additional Notes': '📌',
  'Notes': '📌',
  'Other Insurance': '🛡️',
  'Loyalty & Rewards': '🎁',
  'Tax Information': '🧾',
  'Pending Legal Matters': '⚖️',
  'Life Relay Backup': '💾',
  'Estate Planning': '⚖️',
  'Settings': '⚙️',
}

export function getIcon(sectionName: string): string {
  return SECTION_ICONS[sectionName] || '•'
}

